# Generated by Django 6.0.7 on 2026-07-17 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('machine_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('category', models.CharField(choices=[('machine', 'Machine'), ('descriptive', 'Descriptive')], max_length=16)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number'), ('bool', 'Boolean')], max_length=8)),
                ('is_period', models.BooleanField(default=False, help_text='If true, fact rows for this field carry a period_unit (calendar_days/business_days/months/years).')),
                ('allows_multiple_concurrent', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('maintainer', 'Maintainer'), ('trusted_reviewer', 'Trusted reviewer')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('type', models.CharField(choices=[('city', 'City'), ('county', 'County'), ('hoa', 'HOA'), ('university', 'University'), ('transit', 'Transit authority'), ('other', 'Other')], max_length=16)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('governing_body_name', models.CharField(blank=True, max_length=200)),
                ('meeting_schedule_text', models.TextField(blank=True)),
                ('agenda_url', models.URLField(blank=True)),
                ('records_request_contact', models.CharField(blank=True, help_text='Public-records request URL or email -- free text since either form is valid.', max_length=255)),
                ('fips_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('agenda_platform', models.CharField(blank=True, choices=[('legistar', 'Legistar'), ('granicus', 'Granicus'), ('civicplus', 'CivicPlus'), ('novusagenda', 'NovusAGENDA'), ('primegov', 'PrimeGov'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state', 'type'), name='unique_jurisdiction_name_state_type')],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='registry.vendor')),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(editable=False, max_length=200, unique=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='registry.vendor')),
            ],
            options={
                'ordering': ['alias_text'],
            },
        ),
    ]
