# Generated by Django 6.0.7 on 2026-07-17 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_seed_machine_fact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('master_agreement', 'Master agreement'), ('participating_agreement', 'Participating agreement'), ('standalone_agreement', 'Standalone agreement'), ('task_order', 'Task order')], max_length=24)),
                ('scope_note', models.TextField(blank=True, help_text="Short factual description of what this instrument covers, e.g. 'ALPR cameras, Police Dept'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='registry.jurisdiction')),
                ('parent_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participating_agreements', to='registry.agreement')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='registry.vendor')),
            ],
            options={
                'ordering': ['jurisdiction', 'vendor', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('replaces', 'Replaces'), ('renewed_as_new_procurement', 'Renewed as new procurement'), ('related_department_arrangement', 'Related department arrangement'), ('consolidated_from', 'Consolidated from')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relationships', to='registry.agreement')),
                ('to_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='registry.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('original_agreement', 'Original agreement'), ('amendment', 'Amendment'), ('extension', 'Extension'), ('purchase_order', 'Purchase order'), ('council_approval', 'Council approval'), ('agenda_packet', 'Agenda packet'), ('minutes', 'Minutes'), ('invoice', 'Invoice'), ('records_response', 'Records response'), ('news_article', 'News article')], max_length=24)),
                ('original_url', models.URLField(blank=True)),
                ('archived_storage_key', models.CharField(max_length=500, unique=True)),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a 64-character lowercase hexadecimal SHA-256 digest.', regex='^[a-f0-9]{64}$')])),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('date_obtained', models.DateField()),
                ('acquisition_method', models.CharField(choices=[('public_records_request', 'Public records request'), ('agenda_packet', 'Agenda packet'), ('news_coverage', 'News coverage'), ('vendor_press_release', 'Vendor press release'), ('direct_submission', 'Direct submission'), ('other', 'Other')], max_length=24)),
                ('vote_or_approval_date', models.DateField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('stated_effective_date', models.DateField(blank=True, null=True)),
                ('contains_personal_info', models.BooleanField(default=False)),
                ('redaction_performed_by', models.CharField(blank=True, choices=[('source_agency', 'Source agency'), ('project', 'Project'), ('unknown', 'Unknown')], max_length=16, null=True)),
                ('redaction_note', models.TextField(blank=True)),
                ('unredacted_copy_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('retained_restricted', 'Retained (restricted)'), ('deleted', 'Deleted')], default='not_applicable', max_length=24)),
                ('unredacted_copy_sha256', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Must be a 64-character lowercase hexadecimal SHA-256 digest.', regex='^[a-f0-9]{64}$')])),
                ('unredacted_copy_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unredacted_retention_reason', models.TextField(blank=True)),
                ('unredacted_access_policy', models.CharField(blank=True, max_length=255)),
                ('wayback_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('wayback_attempts', models.PositiveIntegerField(default=0)),
                ('wayback_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('wayback_last_error', models.TextField(blank=True)),
                ('wayback_url', models.URLField(blank=True)),
                ('wayback_saved_at', models.DateTimeField(blank=True, null=True)),
                ('next_archive_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_obtained', 'id'],
                'indexes': [models.Index(fields=['content_sha256'], name='document_sha256_idx'), models.Index(fields=['wayback_status', 'next_archive_attempt_at'], name='document_archive_retry_idx'), models.Index(fields=['document_date'], name='document_document_date_idx'), models.Index(fields=['date_obtained'], name='document_date_obtained_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_role', models.CharField(blank=True, choices=[('governing_instrument', 'Governing instrument'), ('amendment', 'Amendment'), ('approval_record', 'Approval record'), ('pricing_schedule', 'Pricing schedule'), ('supporting_record', 'Supporting record')], max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='registry.agreement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_links', to='registry.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('redacted_version_of', 'Redacted version of'), ('corrected_version_of', 'Corrected version of'), ('ocr_derived_from', 'OCR derived from'), ('duplicate_of', 'Duplicate of'), ('replacement_for', 'Replacement for'), ('attachment_to', 'Attachment to')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relationships', to='registry.document')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relationships', to='registry.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['jurisdiction', 'vendor'], name='agreement_juris_vendor_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(condition=models.Q(('parent_agreement__isnull', True), models.Q(('parent_agreement', models.F('id')), _negated=True), _connector='OR'), name='agreement_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='agreementrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_agreement', models.F('to_agreement')), _negated=True), name='agree_rel_no_self_link'),
        ),
        migrations.AddConstraint(
            model_name='agreementrelationship',
            constraint=models.UniqueConstraint(fields=('from_agreement', 'to_agreement', 'relationship_type'), name='uniq_agree_rel_directional'),
        ),
        migrations.AddConstraint(
            model_name='documentagreement',
            constraint=models.UniqueConstraint(fields=('document', 'agreement'), name='unique_document_agreement_pair'),
        ),
        migrations.AddConstraint(
            model_name='documentrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_document', models.F('to_document')), _negated=True), name='doc_rel_no_self_link'),
        ),
        migrations.AddConstraint(
            model_name='documentrelationship',
            constraint=models.UniqueConstraint(fields=('from_document', 'to_document', 'relationship_type'), name='uniq_doc_rel_directional'),
        ),
    ]
