# Generated by Django 6.0.7 on 2026-07-23 21:10

import django.db.models.deletion
import registry.services.integrity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_agreement_agreementrelationship_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactFieldQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier_key', models.SlugField(max_length=64)),
                ('qualifier_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifiers', to='registry.factfield')),
            ],
            options={
                'ordering': ['field', 'qualifier_key'],
            },
        ),
        migrations.CreateModel(
            name='FactDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_favors_one', 'Resolved (favors one)'), ('resolved_both_partially_correct', 'Resolved (both partially correct)'), ('resolved_unresolved', 'Resolved (left unresolved)')], default='open', max_length=32)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_disputes', to='registry.agreement')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='registry.factfield')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to='registry.reviewer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved', to='registry.reviewer')),
                ('qualifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='registry.factfieldqualifier')),
            ],
            bases=(registry.services.integrity.UndeletableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_period_start', models.DateField(blank=True, null=True)),
                ('scope_period_end', models.DateField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('period_unit', models.CharField(blank=True, choices=[('calendar_days', 'Calendar days'), ('business_days', 'Business days'), ('months', 'Months'), ('years', 'Years')], max_length=16, null=True)),
                ('currency', models.CharField(blank=True, help_text='ISO 4217, e.g. USD.', max_length=3, null=True)),
                ('pricing_basis', models.CharField(blank=True, choices=[('total_contract_value', 'Total contract value'), ('annual_recurring', 'Annual recurring'), ('monthly_recurring', 'Monthly recurring'), ('one_time', 'One time')], max_length=24, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('effective_date_basis', models.CharField(choices=[('stated_in_document', 'Stated in document'), ('execution_date', 'Execution date'), ('approval_date', 'Approval date'), ('unspecified_defaulted', 'Unspecified (defaulted)')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed'), ('retracted', 'Retracted'), ('proposed_option', 'Proposed option')], default='active', max_length=16)),
                ('retraction_reason', models.TextField(blank=True)),
                ('retracted_at', models.DateTimeField(blank=True, null=True)),
                ('page_or_section_reference', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='registry.agreement')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='registry.factfield')),
                ('primary_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_facts', to='registry.document')),
                ('retracted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facts_retracted', to='registry.reviewer')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='registry.fact')),
                ('qualifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='registry.factfieldqualifier')),
            ],
            options={
                'ordering': ['agreement', 'field', '-valid_from'],
            },
            bases=(registry.services.integrity.UndeletableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RequiredFactSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('deadline_confidence', 'Deadline confidence'), ('record_completeness', 'Record completeness')], max_length=24)),
                ('required_when_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_in_sets', to='registry.factfield')),
                ('required_when_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registry.factfield')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('what_was_checked', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='registry.agreement')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications_performed', to='registry.reviewer')),
            ],
            bases=(registry.services.integrity.UndeletableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VerificationFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_links', to='registry.fact')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covered_facts', to='registry.verification')),
            ],
            bases=(registry.services.integrity.UndeletableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactCorroboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corroborated_facts', to='registry.document')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corroborations', to='registry.fact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fact', 'document'), name='uniq_fact_corroboration')],
            },
        ),
        migrations.CreateModel(
            name='FactDisputeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_note', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('under_review', 'Under review'), ('upheld', 'Upheld'), ('rejected', 'Rejected')], default='under_review', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='registry.factdispute')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_memberships', to='registry.fact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dispute', 'fact'), name='uniq_dispute_member')],
            },
            bases=(registry.services.integrity.UndeletableModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='factfieldqualifier',
            constraint=models.UniqueConstraint(fields=('field', 'qualifier_key'), name='uniq_qualifier_per_field'),
        ),
        migrations.AddIndex(
            model_name='factdispute',
            index=models.Index(fields=['agreement', 'field'], name='fact_dispute_agree_field_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['agreement', 'field'], name='fact_agreement_field_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['valid_from', 'valid_until'], name='fact_validity_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['status'], name='fact_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_text__isnull', False), ('value_number__isnull', True), ('value_date__isnull', True), ('value_bool__isnull', True)), models.Q(('value_text__isnull', True), ('value_number__isnull', False), ('value_date__isnull', True), ('value_bool__isnull', True)), models.Q(('value_text__isnull', True), ('value_number__isnull', True), ('value_date__isnull', False), ('value_bool__isnull', True)), models.Q(('value_text__isnull', True), ('value_number__isnull', True), ('value_date__isnull', True), ('value_bool__isnull', False)), _connector='OR'), name='fact_value_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='fact_valid_until_after_from'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('scope_period_start__isnull', True), ('scope_period_end__isnull', True), ('scope_period_end__gte', models.F('scope_period_start')), _connector='OR'), name='fact_scope_period_order'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', True), ('scope_period_end__isnull', True), ('scope_period_start__isnull', True), ('status', 'active')), fields=('agreement', 'field', 'valid_from'), name='uniq_active_fact_bare'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', False), ('status', 'active')), fields=('agreement', 'field', 'qualifier', 'scope_period_start', 'scope_period_end', 'valid_from'), name='uniq_active_fact_qualified'),
        ),
        migrations.AddConstraint(
            model_name='requiredfactset',
            constraint=models.UniqueConstraint(condition=models.Q(('required_when_field__isnull', True)), fields=('purpose', 'field'), name='uniq_required_fact_set_unconditional'),
        ),
        migrations.AddConstraint(
            model_name='requiredfactset',
            constraint=models.UniqueConstraint(condition=models.Q(('required_when_field__isnull', False)), fields=('purpose', 'field', 'required_when_field', 'required_when_value'), name='uniq_required_fact_set_conditional'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['agreement'], name='verification_agreement_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationfact',
            constraint=models.UniqueConstraint(fields=('verification', 'fact'), name='uniq_verification_fact'),
        ),
    ]
