# Generated by Django 6.0.7 on 2026-07-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_factfieldqualifier_factdispute_fact_requiredfactset_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fact',
            name='fact_scope_period_order',
        ),
        migrations.RemoveConstraint(
            model_name='fact',
            name='uniq_active_fact_bare',
        ),
        migrations.RemoveConstraint(
            model_name='fact',
            name='uniq_active_fact_qualified',
        ),
        migrations.AddField(
            model_name='fact',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='facts_created', to='registry.reviewer'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_period_start__isnull', True), ('scope_period_end__isnull', True)), models.Q(('scope_period_start__isnull', False), ('scope_period_end__isnull', False), ('scope_period_end__gte', models.F('scope_period_start'))), _connector='OR'), name='fact_scope_period_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', True), ('scope_period_start__isnull', True), ('status', 'active')), fields=('agreement', 'field', 'valid_from'), name='uniq_active_fact_bare'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', True), ('scope_period_start__isnull', False), ('status', 'active')), fields=('agreement', 'field', 'scope_period_start', 'scope_period_end', 'valid_from'), name='uniq_active_fact_scope_only'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', False), ('scope_period_start__isnull', True), ('status', 'active')), fields=('agreement', 'field', 'qualifier', 'valid_from'), name='uniq_active_fact_qual_only'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('qualifier__isnull', False), ('scope_period_start__isnull', False), ('status', 'active')), fields=('agreement', 'field', 'qualifier', 'scope_period_start', 'scope_period_end', 'valid_from'), name='uniq_active_fact_qual_scope'),
        ),
    ]
